version: '3.8'

services:
  postgres:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: '${PGUSER:-postgres}'
      POSTGRES_PASSWORD: '${PGPASSWORD:-postgres}'
    ports:
      - '${PGPORT:-5432}:5432'
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: 'redis:7-alpine'
    ports:
      - '${REDISPORT:-6379}:6379'
    restart: unless-stopped
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
